#!/bin/bash

# Build & push image to heroku registry
echo "$HEROKU_API_KEY" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
docker build . -t registry.heroku.com/$HEROKU_APP_NAME/web
docker push registry.heroku.com/$HEROKU_APP_NAME/web

# Trigger heroku release
wget -qO- https://toolbelt.heroku.com/install.sh | sh
heroku container:release web --app $HEROKU_APP_NAME
